### ISSUE TITLE
low difficulty share in beta 5 

### ISSUE THREAD

**Issue by SomethingGettingWrong** [TrailingStop/TT-Miner-beta#14]
several of my mahcines show low difficulty shares.(only when first starting) after awhile they dont seem to be appear but that could be to something else. Have a fear if difficulty raises up substanially and you miss a share might result in a lower hashrate overall then the 3 percent speed increase. unsure of the optimizations across the board on all cpus are if it even matters.   However the speed has increased on them in the form of hashrate. by about 3 percent accross the board in hashrate... but.. due to low difficutly shares i feel it was overall faster on the last official release on all cpomtuers ( the one tha tcrashed at 10 mins) you fixed in the beta.

**Comment by SomethingGettingWrong** [comment]
I didnt really get a chance to compare... them as they other one ran 10 mins.. but was just gonna make you aware it is showing low diffculty share. but I just got b5 running on  them all ill reprot back and see how close to actual speed the pool is vs hashrate in miner over next 24 .

**Comment by TrailingStop** [comment]
This is expected. Spectre uses a blocktime of 1 second. That means that you might see on average a new job every second. If a new job comes in the current one becomes invalid.
You will see the first invalid in most cases when the bridge increases the diff since it notices much to many shares from the miner. The bridge assumes that the new diff gets active as soon s it is send, but that is not correct. a new diff gets active for the next job. so TT finds in most cases a new share for the old diff and sends it. this is fixed as soon as a new job comes in.
On the other hand you will see 'low diff' shares from time to time- which are 'staled' shares. you can see that TT receives a new job around the time it finds a new share. This gets then rejected by the bridge as 'low diff', but is jut staled. You cannot avoid this because the blocktime is that low. You can improve the conditions if you have a fast network and a good connection to the internet to keep changes of stales low. Make sure the RT value i s low as possible.

**Comment by SomethingGettingWrong** [comment]
sounds legit. Good work  You do on everything bro.  Thanks again.
